### ISSUE TITLE
Ресторан: инициализация

### ISSUE THREAD

**Issue by LukoninDmitryPy** [bronfood-com/backend#25]
1. Создание модели.
2. Мин. функционал для дальнейшей работы.

доработать ПР:
https://github.com/bronfood-com/backend/pull/26

**Comment by kmvpw** [comment]
Как успехи?

**Comment by syberflea** [comment]
Сделал минимальную модель, т.е. то, что можно обсуждать, см. [ПР26.](https://github.com/bronfood-com/backend/pull/26#issue-2010668664) Последние две недели занимался другими ПР.
