### ISSUE TITLE
Создать кастомные auth backend

### ISSUE THREAD

**Issue by lekirill** [bronfood-com/backend#33]
Создать кастомные auth backend в core/auth_backends.py

2. PhoneBackend: работает для клиента и владельца ресторана, проверка пароля и телефона
3. UsernameBackend: работает для админа ресторана, проерка пароля и юзернэйм

Добавить в settings:

AUTHENTICATION_BACKENDS = [
    'bronfood.auth_backends.PhoneBackend', 
    'bronfood.auth_backends.UsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

**Comment by kmvpw** [comment]
Что удалось реализовать?

**Comment by syberflea** [comment]
Сделал начальный минимум. Ветку не публиковал. Проверю ещё раз - опубликую.

**Comment by syberflea** [comment]
Тикет закрыт.
