### ISSUE TITLE
Изменение профиля

### ISSUE THREAD

**Issue by kmvpw** [bronfood-com/backend#79]
По новым водным от заказчика поделили обновление профиля на профиль и пароль.
Переделать профиль без пароля.
Сделать API для изменения пароля.

**Comment by Solodnikov** [comment]
Устранил ошибку, возникавшую при валидации переданных данных при изменении профиля. Теперь можно изменять любые данные пользователя без указания пароля и подтверждения пароля (не обязательны).
Как сообщили фронты и фигма подтверждает - отказались от идеи разделения на отдельные экраны личные сведения и смена пароля
